version: '3.5'
services:
    app:
        image: hanabosocom/php-dev:php-8.1-alpine
        user: ${DEV_UID}:${DEV_GID}
        ports:
            - ${DEV_IP}:8000:80
        working_dir: /var/www/pipes/pipes-connectors
        volumes:
            - ../:/var/www/pipes:cached
            - ${SSH_AUTH}:/tmp/.ssh-auth-sock
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - KERNEL_CLASS=HbPFConnectorsTests\app\Kernel
            - PHP_WEBROOT=/var/www/pipes/pipes-connectors/public
            - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
            - COMPOSER_HOME=${HOME}/dev/.composer

    mongo:
        image: mongo:latest
        ports:
            - ${DEV_IP}:27017:27017
        volumes:
            - mongo:/data/db

    fakes3:
        image: olalond3/fakes3

volumes:
    mongo: {}
